
import {
  LayoutDashboard,
  House,
  FileText,
  Settings,
  BookOpen,
  Search,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Sparkles,
  Database,
  Languages,
  ArrowRightLeft,
  Wand2,
  Lock,
  Unlock,
  MoreVertical,
  Download,
  Upload,
  RefreshCw,
  Edit3,
  Trash2,
  Plus,
  Save,
  Zap,
  BrainCircuit,
  ClipboardCheck,
  AlertTriangle,
  AlertCircle,
  Wrench,
  ScanSearch,
  PanelLeftClose,
  PanelLeftOpen,
  ArrowUpDown,
  CornerDownRight,
  BookDashed,
  Copy,
  HelpCircle,
  MessageSquare,
  Lightbulb,
  Scissors as ScissorsIcon,
  User,
  UserPlus,
  Brain,
  BookOpen as BookOpenIcon,
  Superscript,
  Subscript,
  RemoveFormatting,
  Eraser,
  Paintbrush,
  Merge,
  Globe,
  Bookmark,
  ExternalLink,
  Brackets,
  CaseSensitive,
  ArrowUpToLine,
  ArrowDownToLine
} from 'lucide-react';

export const Icons = {
  Home: House,
  Dashboard: LayoutDashboard,
  File: FileText,
  Settings: Settings,
  TermBase: BookOpen,
  Search: Search,
  Check: Check,
  X: X,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ChevronDown: ChevronDown,
  Sparkles: Sparkles,
  Database: Database,
  Languages: Languages,
  Translate: ArrowRightLeft,
  Magic: Wand2,
  Lock: Lock,
  Unlock: Unlock,
  More: MoreVertical,
  Download: Download,
  Upload: Upload,
  Refresh: RefreshCw,
  Edit: Edit3,
  Trash: Trash2,
  Plus: Plus,
  Save: Save,
  Zap: Zap,
  BrainCircuit: BrainCircuit,
  QA: ClipboardCheck,
  ClipboardCheck: ClipboardCheck,
  Warning: AlertTriangle,
  Info: AlertCircle,
  Wrench: Wrench,
  TermExtraction: ScanSearch,
  ScanSearch: ScanSearch,
  SidebarClose: PanelLeftClose,
  SidebarOpen: PanelLeftOpen,
  Sort: ArrowUpDown,
  Jump: CornerDownRight,
  CornerDownRight: CornerDownRight,
  Concordance: BookDashed,
  Copy: Copy,
  HelpCircle: HelpCircle,
  MessageSquare: MessageSquare,
  Lightbulb: Lightbulb,
  Scissors: ScissorsIcon,
  // 新增的图标
  User: User,
  UserPlus: UserPlus,
  Brain: Brain,
  BookOpen: BookOpenIcon,
  AlertTriangle: AlertTriangle,
  Superscript: Superscript,
  Subscript: Subscript,
  RemoveFormatting: RemoveFormatting,
  Eraser: Eraser,
  Paintbrush: Paintbrush,
  Merge: Merge,
  Globe: Globe,
  Bookmark: Bookmark,
  ExternalLink: ExternalLink,
  RegexDict: Brackets,
  CaseSensitive: CaseSensitive,
  ArrowUpToLine: ArrowUpToLine,
  ArrowDownToLine: ArrowDownToLine
};